### ISSUE TITLE
1.2.1 Scan Book

### ISSUE THREAD

**Issue by jeffkirker** [cmput301w19t23/BooKeep#2]
Name | ScanBook
-- | --
Participating Actors | Book Owner
Goal | To get the description of the book by scanning the barcode
Trigger | Book Owner clicks the "Scan Book" button
Precondition | Book Owner is on the "Add Book" page
Postcondition | The book description gets filled up automatically
Basic Flow | System opens camera and waits for a barcode to appearBook owner points camera at the books barcodeSystem captures barcode and auto-fills the book description form
Exceptions |  
Notes |  
Related Artifacts | US 01.02.01
Value | 5

**Comment by hughbagan** [comment]
Fixed the Camera permissions, scanning should be finished now
